### ISSUE TITLE
Can you provide small example?

### ISSUE THREAD

**Issue by eouia** [awernick/google-assistant-node#2]
I've tried to implement this code, but failed.
Can you show the sample script to learn how it works?

**Comment by ghost** [comment]
have you been successful?

**Comment by eouia** [comment]
@DaniVarga This is a closed issue, so I aware... And sorry for owner of this repository.
I used another node module for implementation and got success.

**Comment by awernick** [comment]
@DaniVarga @eouia I'm not sure what type of example you need. The README contains the basic flow of the module. If you need a more concrete example, I could add some scripts that output audio using the `speaker` module.

**Comment by awernick** [comment]
I have added an example script showing how to record audio using the internal microphone and listening to the Assistant's response through the speakers. Please let me know if you have any other questions. I would be more than happy to walk you through any issues!
